### PR TITLE
Build script mod

### LINKED ISSUE #8: Docs update: How to make PuTTY show all rt-ps glyphs in Windows
Download and install these two fonts.

<b>EverMono</b>
http://www.evertype.com/emono/
http://www.evertype.com/emono/evermono.zip

<b>DejaVu Sans Mono</b>
http://dejavu-fonts.org/wiki/Download
http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.zip

Use <b>font linking</b> to make EverMono complement DevaVu Sans Mono.

Add (or Edit) a multi-string value for your preferred font under the Windows registry key

Start <b>Regedit</b>. Go to the key below.

> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink

The added (or edited) key name should be the font name, and the value associated is a list of fallback font options to display the characters not recognized by previous font. There should be some existing ones, you can copy the value from there. Or, add a new Multi String key.

That's what you should do.
Right click <b><i>SystemLink</i></b> and select <b><i>New</i></b>, then <b><i>Multi String Value</i></b>.
Name it <b>DejaVu Sans Mono</b>.

After it's been created, double-click it and enter this inside.
<b>Everson Mono.ttf,EversonMono</b>

At the very least you must logout from Windows and back in again to activate this font link, but I recommend a full reboot.

Now, after rebooting, with PuTTY running change the settings for fonts. Click the PuTTY icon, top-left on your PuTTY window, and then <b><i>Change settings</i></b>. Go to <b><i>Window / Appearance</i></b> and select <b>DejaVu Sans Mono</b>.

<b>Now your rtorrent-PS should look as beautiful as pyroscope always intended it!</b>

Base info taken from 
http://superuser.com/questions/393834/how-to-configure-putty-to-display-these-characters/764855#764855
Complemented with the MSDN doc linked therein.
https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx

### PR DESCRIPTION
**Pull request by chros73**
Build script mod (Closes chros73#8)

### CODE REVIEW

**Comment by pyroscope** [comment]
#8 seems quite unrelated.

**Comment by chros73** [comment]
> #8 seems quite unrelated.

Errr... :) That's the problem you mentioned earlier: the beginning I left the `Closes ...` text in the title.
I meant: https://github.com/chros73/rtorrent-ps/issues/8
So please check always the body of the ticket.
Sorry about the confusion.

**Comment by pyroscope** [comment]
These files are certainly needed if you do more than one-shot builds.

**Comment by chros73** [comment]
I've edited those titles just now.

**Comment by chros73** [comment]
>  if you do more than one-shot builds.

How would you do this? Why? (We can go to chat now.)

**Pull request closed without merging**
