### PR TITLE
Fix scheduled sorting/filtering bug on started and stopped views in rtorrent

### PR DESCRIPTION
**Pull request by chros73**
Fixes: https://github.com/rakshasa/rtorrent/issues/449
Refers to: https://github.com/chros73/rtorrent-ps/issues/19

I've also created a pull request in `rtorrent` project for this, but who knows what will happen to it. :) We can remove it later if it will be accepted.
https://github.com/rakshasa/rtorrent/pull/451

### CODE REVIEW

**Comment by pyroscope** [comment]
I might add this before mainline does, but I hope you DO realize there's an easier way: make 2 new views (they're different anyway), and rebind key 3 + 4 to show *those* views.

**Comment by chros73** [comment]
:) Of course, but that doesn't fix this critical bug in the client itself.

**Comment by chros73** [comment]
Note: under "all" in the patch name I understand version >= 0.9.2 (as the current build script works). I don't know how this patch behaves with versions before this (I haven't checked).

**Comment by pyroscope** [comment]
I removed pre-092 a while ago anyway, I think. If anyone wants the stoneage, they can check out old revisions.

**Pull request merged**
